name: Push Check

on: [push]

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                  node-version: "20"
                  cache: "yarn"
            - run: yarn
            - run: yarn test
            - run: yarn build
